### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by tmedani** [ajoshiusc/deface_mri#2]
Performing affine registration with 12 degrees of freedom...
Search-based initialization... Undefined function or variable 'affine_transform_3dvol_double'.

Error in register_volumes_affine (line 199)
         Imoved = affine_transform_3dvol_double(sm_mov_img, M, 1, opts.nthreads);

Error in register_files_affine (line 449)
[~, x, Ireg] = register_volumes_affine(mImg, sImg, m_mask, s_mask, opts.reg_res, reg_opt);

Error in deface_mri (line 46)
[M_world, ref_loc] = register_files_affine(atlas_bse,mri_bse, out_img, opts);

**Comment by ajoshiusc** [comment]
should be fixed now. added mex file that was required.
